### Pandas
**Pandas is a high-level data manipulation library built on top of NumPy**, designed for:
- Tabular data (rows & columns)
- Labeled data (named columns + index)
- Fast vectorized operations
- Data cleaning, transformation, aggregation

### Core Building Blocks
Pandas has two fundamental data structures:
1. **Series** → 1D labeled array (column)
2. **DataFrame** → 2D labeled table (collection of Series)

In [1]:
import pandas as pd

In [2]:
scores = pd.Series([85, 90, 78])
scores

0    85
1    90
2    78
dtype: int64

#### Custom Index

In [3]:
scores = pd.Series([85, 90, 78], index=["Math", "Science", "English"])
scores

Math       85
Science    90
English    78
dtype: int64

**Important:**
Index is *not* just position - it's a **first-class concept** in Pandas.

Pandas treats the index as first-class because it enables **automatic data alignment, joins, time-based operations, and safe transformations without relying on position.**

**Real-world example:**
- User IDs
- Timestamps
- Transaction IDs

#### Seres behave like NumPy + Dict

In [4]:
scores.max()

np.int64(90)

In [5]:
scores["Math"]

np.int64(85)

### Pandas DataFrame
A DataFrame is:
- A table of rows & columns
- Each column is a Series
- All columns share the same index

In [6]:
data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "salary": [50000, 60000, 70000]
}

df = pd.DataFrame(data)
df

      name  age  salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [8]:
df["age"] # returns Series

0    25
1    30
2    35
Name: age, dtype: int64

In [9]:
df[["name", "salary"]] # returns DataFrame

      name  salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000

### DataFrame vs Series
| Feature    | Series          | DataFrame       |
| ---------- | --------------- | --------------- |
| Dimensions | 1D              | 2D              |
| Labels     | Index           | Index + Columns |
| Use case   | Single variable | Dataset / table |

**Pandas is Powerful because:**
- Vectorization
- Label-based alignment
- Rich ecosystem

In [10]:
s1 = pd.Series([1, 2, 3], index=["a", "b", "c"])
s2 = pd.Series([10, 20, 30], index=["b", "c", "d"])

s1 + s2

a     NaN
b    12.0
c    23.0
d     NaN
dtype: float64

### Exercise 1
Create a Pandas `Series` named `temps` with values `[28, 30, 27, 29]`.
1. What is the default index?
2. What is the dtype?
3. What will `temps.mean()` return?

In [13]:
temps = pd.Series([28, 30, 27, 29])
print(temps)
print(temps.mean())

0    28
1    30
2    27
3    29
dtype: int64
28.5

### Exercise 2
Create a `Series` for marks:

| Subject   | Marks |
| --------- | ----- |
| Math      | 88    |
| Physics   | 92    |
| Chemistry | 85    |

In [17]:
marks = pd.Series([88, 92, 85], index=["Math", "Physics", "Chemistry"])
print(marks)
print(marks["Physics"])
print(marks[0])

Math         88
Physics      92
Chemistry    85
dtype: int64
92
88

/var/folders/6t/gr1hsb2x571bqm8sycqy4h440000gn/T/ipykernel_3650/3318852799.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])

### Exercise 3
Create a DataFrame `students`:
| name | age | city   |
| ---- | --- | ------ |
| Asha | 21  | Pune   |
| Ravi | 23  | Mumbai |
| Neha | 22  | Delhi  |

In [22]:
data = {
    "name": ["Asha", "Ravi", "Neha"],
    "age": [21, 23, 22],
    "city": ["Pune", "Mumbai", "Delhi"]
}

students = pd.DataFrame(data)
students

   name  age    city
0  Asha   21    Pune
1  Ravi   23  Mumbai
2  Neha   22   Delhi

In [25]:
print(students["age"])
print(students[["name", "city"]])

0    21
1    23
2    22
Name: age, dtype: int64
   name    city
0  Asha    Pune
1  Ravi  Mumbai
2  Neha   Delhi

### Exercise 4
Given:
```python
df = pd.DataFrame({
    "A": [10, 20],
    "B": [30, 40]
})
```

Answer:
1. How many Series does this DataFrame contain?
2. What does df["A"] + df["B"] return?
3. What does df.mean() compute?

In [27]:
df = pd.DataFrame({
    "A": [10, 20],
    "B": [30, 40]
})
df

# Contains 2 Series

    A   B
0  10  30
1  20  40

In [29]:
print(df["A"] + df["B"])
print(df.mean())

0    40
1    60
dtype: int64
A    15.0
B    35.0
dtype: float64

### Exercise 5
Predict the output:
```python
s1 = pd.Series([5, 10], index=["x", "y"])
s2 = pd.Series([3, 7], index=["y", "z"])

s1 + s2
```

In [30]:
s1 = pd.Series([5, 10], index=["x", "y"])
s2 = pd.Series([3, 7], index=["y", "z"])

s1 + s2

x     NaN
y    13.0
z     NaN
dtype: float64

### Exercise 6
Given:
```python
scores = pd.Series([90, 80, 70], index=["A", "B", "C"])
```
What happens if you do: scores["D"]?

In [32]:
scores = pd.Series([90, 80, 70], index=["A", "B", "C"])
print(scores["D"])

KeyError: 'D'

### Exercise 7
What is the output and why?
```python 
s = pd.Series([1, 2, 3])
s + 5
```

In [ ]:
s = pd.Series([1, 2, 3])
s + 5

0    6
1    7
2    8
dtype: int64