### Creating a Series

#### 1. From a Python List

In [1]:
import pandas as pd

In [2]:
s = pd.Series([10, 20, 30])
s

0    10
1    20
2    30
dtype: int64

#### 2. With Explicit `dtype`

In [3]:
s = pd.Series([10, 20, 30], dtype="int32")
s

0    10
1    20
2    30
dtype: int32

#### 3. From a Dictionary

In [4]:
s = pd.Series({
    "a": 100,
    "b": 200,
    "c": 300
})
s

a    100
b    200
c    300
dtype: int64

#### 4. From NumPy Array

In [5]:
import numpy as np

arr = np.array([1.5, 2.5, 3])
s = pd.Series(arr)
s

0    1.5
1    2.5
2    3.0
dtype: float64

### Creating a DataFrame

#### 1. From a Dictionary of Lists

In [6]:
data = {
    "name": ["Asha", "Ravi", "Neha"],
    "age": [21, 23, 22],
    "salary": [40000, 50000, 45000]
}

df = pd.DataFrame(data)
df

   name  age  salary
0  Asha   21   40000
1  Ravi   23   50000
2  Neha   22   45000

#### 2. Explicit Column Order

In [7]:
df = pd.DataFrame(data, columns=["name", "salary", "age"])
df

   name  salary  age
0  Asha   40000   21
1  Ravi   50000   23
2  Neha   45000   22

#### 3. From List of Dictionaries

In [8]:
records = [
    {"name": "Asha", "age": 21, "city": "Pune"},
    {"name": "Ravi", "age": 23, "city": "Mumbai"},
    {"name": "Neha", "age": 22, "city": "Delhi"}
]

df = pd.DataFrame(records)
df

   name  age    city
0  Asha   21    Pune
1  Ravi   23  Mumbai
2  Neha   22   Delhi

#### 4. Missing Keys in Dicts

In [9]:
records = [
    {"name": "Asha", "age": 21},
    {"name": "Ravi", "city": "Mumbai"},
]

df = pd.DataFrame(records)
df

   name   age    city
0  Asha  21.0     NaN
1  Ravi   NaN  Mumbai

### Creating DataFrame From NumPy Arrays

#### 1 . Simple Example

In [10]:
arr = np.array([[1, 2],
                [3, 4]])

df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4

#### 2. Control Index & Columns

In [11]:
df = pd.DataFrame(
    arr, 
    index=["row1", "row2"],
    columns=["col1", "col2"]
)

df

      col1  col2
row1     1     2
row2     3     4

### `dtype` Control

#### Automatic Inference Pitfall

In [12]:
df = pd.DataFrame({
    "id": [1, 2, 3],
    "score": [90, None, 85]
})

df.dtypes

id         int64
score    float64
dtype: object

Integer column became float due to `NaN`.

#### Correct Way

In [13]:
df = pd.DataFrame({
    "id": pd.Series([1, 2, 3], dtype="int64"),
    "score": pd.Series([90, None, 85], dtype="Int64")
})

df.dtypes

id       int64
score    Int64
dtype: object

`Int64` supports missing values.

### Exercise 1
Create a `Series` named `prices` from the list `[100, 200, 150, 300]`.
1. Check the default index
2. Explicitly set dtype to float64
3. Convert it to int64 afterward

In [14]:
prices = pd.Series([100, 200, 150, 300])
prices.dtype

prices = pd.Series([100, 200, 150, 300], dtype='float64')
prices.dtype

prices = prices.astype("int64")
prices.dtype

dtype('int64')

### Exercise 2
Create a `Series` from the dictionary:
```python
{"apple": 10, "banana": 20, "orange": 15}
```

1. What becomes the index?
2. Access the value of "banana"

In [15]:
s = pd.Series(
    {"apple": 10, 
     "banana": 20, 
     "orange": 15}
)
print(s)
print(s['banana'])

apple     10
banana    20
orange    15
dtype: int64
20

### Exercise 3
Create a DataFrame `employees`:

| emp_id | name   | dept    |
| ------ | ------ | ------- |
| 101    | Anil   | IT      |
| 102    | Sunita | HR      |
| 103    | Karan  | Finance |


1. Print only the name column
2. Print emp_id and dept together
3. Check the dtypes

In [17]:
data = [
    {"emp_id": 101, "name": "Anil", "dept": "IT"},
    {"emp_id": 102, "name": "Sunita", "dept": "HR"},
    {"emp_id": 103, "name": "Karan", "dept": "Finance"}
]

df = pd.DataFrame(data)
print(df["name"])
print(df[["emp_id", "dept"]])

0      Anil
1    Sunita
2     Karan
Name: name, dtype: object
   emp_id     dept
0     101       IT
1     102       HR
2     103  Finance

### Exercise 4
Create the same `employees` DataFrame using a list of dictionaries

In [ ]:
data = {
    "emp_id": [101, 102, 103],
    "name": ["Anil", "Sunita", "Karan"],
    "dept": ["IT", "HR", "Finance"]
}

df = pd.DataFrame(data)
df

   emp_id    name     dept
0     101    Anil       IT
1     102  Sunita       HR
2     103   Karan  Finance

### Exercise 5
Create a DataFrame from:
```python
[
    {"id": 1, "score": 90},
    {"id": 2},
    {"id": 3, "score": 85}
]
```
1. What is the dtype of `score`?
2. Why did Pandas choose that dtype?

In [22]:
data = [
    {"id": 1, "score": 90},
    {"id": 2},
    {"id": 3, "score": 85}
]

df = pd.DataFrame(data)
df["score"]

0    90.0
1     NaN
2    85.0
Name: score, dtype: float64

### Exercise 6
Recreate Exercise 5 but:
- Ensure `score` uses nullable integer dtype
- Print dtypes to verify

In [23]:
data = [
    {"id": 1, "score": 90},
    {"id": 2},
    {"id": 3, "score": 85}
]

df = pd.DataFrame(data)
df["score"] = df["score"].astype("Int64")
df["score"].dtype

Int64Dtype()

### Exercise 7
Create a DataFrame from:
```python
{
    "product": ["Laptop", "Mouse", "Keyboard"],
    "price": [70000, 500, 1500]
}
```
Set the index as: `["P1", "P2", "P3"]`
- Access the price of `"P2"`
- What is the advantage of this index over default index?

In [28]:
data = {
    "product": ["Laptop", "Mouse", "Keyboard"],
    "price": [70000, 500, 1500]
}

df = pd.DataFrame(data, index=["P1", "P2", "P3"])
df.loc["P2", "price"]

np.int64(500)

### Exercise 8
Why this code is production unsafe?
```python
pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5]
})
```

**It will raise an error**

**ValueError:** All arrays must be of same length

**Important:** True misalignment happens** with list-of-dicts, not dict-of-lists.