### Quick Recap
| Concept      | Meaning                     |
| ------------ | --------------------------- |
| **Index**    | Labels (not positions)      |
| **Position** | Integer location (0, 1, 2…) |
| Pandas       | Prefers **labels first**    |

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "name": ["Asha", "Ravi", "Neha"],
    "age": [21, 23, 22],
    "city": ["Pune", "Mumbai", "Delhi"]
}, index=["u1", "u2", "u3"])

df

    name  age    city
u1  Asha   21    Pune
u2  Ravi   23  Mumbai
u3  Neha   22   Delhi

In [3]:
df["age"] # Series

u1    21
u2    23
u3    22
Name: age, dtype: int64

In [4]:
df[["name", "city"]] # DataFrame

    name    city
u1  Asha    Pune
u2  Ravi  Mumbai
u3  Neha   Delhi

### `.loc` - Label-Based Indexing
Syntax: 
```python
df.loc[row_label, column_label]
```

In [5]:
df.loc["u1"]

name    Asha
age       21
city    Pune
Name: u1, dtype: object

In [6]:
df.loc["u1", "age"]

np.int64(21)

In [7]:
df.loc[["u1", "u3"], ["name", "city"]]

    name   city
u1  Asha   Pune
u3  Neha  Delhi

### Label-Based Slicing
**Important: It is inclusive of both ends**

In [8]:
df.loc["u1":"u3"]

    name  age    city
u1  Asha   21    Pune
u2  Ravi   23  Mumbai
u3  Neha   22   Delhi

### `.iloc` - Position-Based Indexing
Syntax
```python
df.iloc[row_position, column_position]
```

In [9]:
df.iloc[0]

name    Asha
age       21
city    Pune
Name: u1, dtype: object

In [10]:
df.iloc[0, 1] # age of first row

np.int64(21)

In [11]:
df.iloc[:, 1:] # all rows, columns from position 1

    age    city
u1   21    Pune
u2   23  Mumbai
u3   22   Delhi

#### Position-Based Slicing
**Important: End is exclusive**

In [12]:
df.iloc[0:2]

    name  age    city
u1  Asha   21    Pune
u2  Ravi   23  Mumbai

### `.at` & `.iat` - Fast Scalar Access
Used when accessing **single values.**

|Method|Based On|Speed|
|----|-----|--------|
|`at`|label|very fast|
|`iat`|position|very fast|

In [13]:
df.at["u2", "city"]

'Mumbai'

In [14]:
df.iat[1, 2]

'Mumbai'

### Boolean Indexing

In [15]:
df[df["age"] > 21]

    name  age    city
u2  Ravi   23  Mumbai
u3  Neha   22   Delhi

#### Equivalent (preferred):

In [16]:
df.loc[df["age"] > 21]

    name  age    city
u2  Ravi   23  Mumbai
u3  Neha   22   Delhi

#### Multiple Conditions

In [17]:
df.loc[(df["age"] > 21) & (df["city"] == "Mumbai")]

    name  age    city
u2  Ravi   23  Mumbai

**Important**

Always use:
- `&`, `|`, Parantheses

### `.query()` - Clean, SQL - like Filters

In [18]:
df.query("age > 21 and city == 'Mumbai'")

    name  age    city
u2  Ravi   23  Mumbai

### Chained Indexing
Avoid this - may fail

In [19]:
df[df["age"] > 21]["city"] = "Bangalore"

/var/folders/6t/gr1hsb2x571bqm8sycqy4h440000gn/T/ipykernel_2196/426430582.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df["age"] > 21]["city"] = "Bangalore"

#### Correct Way

In [20]:
df.loc[df["age"] > 21, "city"] = "Bangalore"
df

    name  age       city
u1  Asha   21       Pune
u2  Ravi   23  Bangalore
u3  Neha   22  Bangalore

In [21]:
# ML feature engineering
df.loc[df["age"] < 18, "is_minor"] = 1
df.loc[df["age"] >= 18, "is_minor"] = 0
df

    name  age       city  is_minor
u1  Asha   21       Pune       0.0
u2  Ravi   23  Bangalore       0.0
u3  Neha   22  Bangalore       0.0

### Summary Table
| Task                    | Use               |
| ----------------------- | ----------------- |
| Select by label         | `loc`             |
| Select by position      | `iloc`            |
| Single value (label)    | `at`              |
| Single value (position) | `iat`             |
| Filtering rows          | `loc` + condition |
| Assignment              | `loc`             |

### Exercise 1
1. Select the row with index `"u2"`
2. Select only the "salary" of `"u3"`
3. Select `"name"` and `"city"` columns for all rows

**DataFrame:**
```python
df = pd.DataFrame({
    "name": ["Asha", "Ravi", "Neha", "Kunal"],
    "age": [21, 23, 22, 24],
    "city": ["Pune", "Mumbai", "Delhi", "Pune"],
    "salary": [40000, 50000, 45000, 55000]
}, index=["u1", "u2", "u3", "u4"])
```

In [29]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Asha", "Ravi", "Neha", "Kunal"],
    "age": [21, 23, 22, 24],
    "city": ["Pune", "Mumbai", "Delhi", "Pune"],
    "salary": [40000, 50000, 45000, 55000]
}, index=["u1", "u2", "u3", "u4"])

In [31]:
df.loc["u2"]

name        Ravi
age           23
city      Mumbai
salary     50000
Name: u2, dtype: object

In [32]:
df.loc["u3", "salary"]

np.int64(45000)

In [33]:
df.loc[:, ["name", "city"]]

     name    city
u1   Asha    Pune
u2   Ravi  Mumbai
u3   Neha   Delhi
u4  Kunal    Pune

### Exercise 2
1. Select the first two rows using `iloc`
2. Select rows `"u2"` to `"u4"` using `loc`
3. Select the last column using `iloc`

In [34]:
df.iloc[:2]

    name  age    city  salary
u1  Asha   21    Pune   40000
u2  Ravi   23  Mumbai   50000

In [35]:
df.loc["u2":"u4"]

     name  age    city  salary
u2   Ravi   23  Mumbai   50000
u3   Neha   22   Delhi   45000
u4  Kunal   24    Pune   55000

In [36]:
df.iloc[:, -1]

u1    40000
u2    50000
u3    45000
u4    55000
Name: salary, dtype: int64

### Exercise 3
1. Select employees with salary > 45000
2. Select employees from Pune with age > 22
3. Select only `name` and `salary` for employees older than 22

In [37]:
df.loc[df["salary"] > 45000]

     name  age    city  salary
u2   Ravi   23  Mumbai   50000
u4  Kunal   24    Pune   55000

In [38]:
df.loc[(df["age"]> 22) &(df["city"] == "Pune")]

     name  age  city  salary
u4  Kunal   24  Pune   55000

In [39]:
df.loc[df["age"]> 22, ["name", "salary"]]

     name  salary
u2   Ravi   50000
u4  Kunal   55000

### Exercise 4
1. Create a new column is_senior
    - 1 if age >= 23
    - 0 otherwise
2. Update city to "Bangalore" for employees earning more than 50000

In [40]:
df.loc[df["age"] >= 23, "is_senior"] = 1
df.loc[df["age"] < 23, "is_senior"] = 0
df

# df["is_senior"] = (df["age"] >= 23).astype(int)

     name  age    city  salary  is_senior
u1   Asha   21    Pune   40000        0.0
u2   Ravi   23  Mumbai   50000        1.0
u3   Neha   22   Delhi   45000        0.0
u4  Kunal   24    Pune   55000        1.0

### Exercise 5
1. Get the salary of `"u4"` using the fastest possible method
2. Get the city of the second row using position-based access

In [41]:
df.at["u4", "salary"]
df.iat[1, 2]

'Mumbai'

### Exercise 6
What is wrong with this code? Fix it.
```python
df[df["city"] == "Pune"]["salary"] = df["salary"] * 1.1
```

In [42]:
df.loc[df["city"] == "Pune", "salary"] *= 1.1

/var/folders/6t/gr1hsb2x571bqm8sycqy4h440000gn/T/ipykernel_2196/509380346.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[44000. 60500.]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df["city"] == "Pune", "salary"] *= 1.1