In [82]:
import pandas as pd

df = pd.DataFrame({
    "user_id": [101, 102, 103, 104, 105],
    "age": [25, 30, None, 22, 28],
    "city": ["Pune", "Mumbai", "Delhi", "Pune", None],
    "salary": [50000, 60000, 55000, 48000, 52000],
    "joined_on": ["2023-01-10", "2022-11-05", "2023-03-20", "2023-01-25", "2022-12-15"]
})

### `head()` & `tail()`
default 5 rows

In [83]:
df.head()

   user_id   age    city  salary   joined_on
0      101  25.0    Pune   50000  2023-01-10
1      102  30.0  Mumbai   60000  2022-11-05
2      103   NaN   Delhi   55000  2023-03-20
3      104  22.0    Pune   48000  2023-01-25
4      105  28.0    None   52000  2022-12-15

In [84]:
df.tail()

   user_id   age    city  salary   joined_on
0      101  25.0    Pune   50000  2023-01-10
1      102  30.0  Mumbai   60000  2022-11-05
2      103   NaN   Delhi   55000  2023-03-20
3      104  22.0    Pune   48000  2023-01-25
4      105  28.0    None   52000  2022-12-15

In [85]:
df.head(2)

   user_id   age    city  salary   joined_on
0      101  25.0    Pune   50000  2023-01-10
1      102  30.0  Mumbai   60000  2022-11-05

In [86]:
df.tail(2)

   user_id   age  city  salary   joined_on
3      104  22.0  Pune   48000  2023-01-25
4      105  28.0  None   52000  2022-12-15

### Shape, Columns & Index

In [87]:
df.shape

(5, 5)

In [88]:
df.columns

Index(['user_id', 'age', 'city', 'salary', 'joined_on'], dtype='object')

In [89]:
df.index

RangeIndex(start=0, stop=5, step=1)

### `info()`

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    5 non-null      int64
 1   age        4 non-null      float64
 2   city       4 non-null      object
 3   salary     5 non-null      int64
 4   joined_on  5 non-null      object
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

`info()` tells you:
- Non-null counts
- Dtypes
- Memory usage

### `describe()` - Satistical Summary

In [91]:
df.describe()

          user_id    age       salary
count    5.000000   4.00      5.00000
mean   103.000000  26.25  53000.00000
std      1.581139   3.50   4690.41576
min    101.000000  22.00  48000.00000
25%    102.000000  24.25  50000.00000
50%    103.000000  26.50  52000.00000
75%    104.000000  28.50  55000.00000
max    105.000000  30.00  60000.00000

Shows:
- count
- mean
- std
- min/max
- quartiles

Numeric columns only by default.

#### Include non-numerics:

In [92]:
df.describe(include='all')

           user_id    age  city       salary   joined_on
count     5.000000   4.00     4      5.00000           5
unique         NaN    NaN     3          NaN           5
top            NaN    NaN  Pune          NaN  2023-01-10
freq           NaN    NaN     2          NaN           1
mean    103.000000  26.25   NaN  53000.00000         NaN
std       1.581139   3.50   NaN   4690.41576         NaN
min     101.000000  22.00   NaN  48000.00000         NaN
25%     102.000000  24.25   NaN  50000.00000         NaN
50%     103.000000  26.50   NaN  52000.00000         NaN
75%     104.000000  28.50   NaN  55000.00000         NaN
max     105.000000  30.00   NaN  60000.00000         NaN

### Checking Missing Data

In [93]:
df.isna()

   user_id    age   city  salary  joined_on
0    False  False  False   False      False
1    False  False  False   False      False
2    False   True  False   False      False
3    False  False  False   False      False
4    False  False   True   False      False

In [94]:
df.isna().sum()

user_id      0
age          1
city         1
salary       0
joined_on    0
dtype: int64

### Value Counts - Categorical Insight

In [95]:
df["city"].value_counts()

city
Pune      2
Mumbai    1
Delhi     1
Name: count, dtype: int64

In [96]:
# Include missing:
df["city"].value_counts(dropna=False)

city
Pune      2
Mumbai    1
Delhi     1
None      1
Name: count, dtype: int64

Used heavily in:
- Data validation
- Feature engineering
- Business logic

### Unique Values and Cardinality

In [97]:
df["city"].unique()

array(['Pune', 'Mumbai', 'Delhi', None], dtype=object)

In [98]:
df["city"].nunique()

3

### Sampling Data

In [99]:
df.sample(2)

   user_id   age    city  salary   joined_on
1      102  30.0  Mumbai   60000  2022-11-05
2      103   NaN   Delhi   55000  2023-03-20

#### Reproducible Sampling:

In [100]:
df.sample(2, random_state=42)

   user_id   age    city  salary   joined_on
1      102  30.0  Mumbai   60000  2022-11-05
4      105  28.0    None   52000  2022-12-15

### Data Type Sanity Check

In [101]:
df.dtypes

user_id        int64
age          float64
city          object
salary         int64
joined_on     object
dtype: object

In [102]:
df["joined_on"] = pd.to_datetime(df["joined_on"])

In [103]:
df.dtypes

user_id               int64
age                 float64
city                 object
salary                int64
joined_on    datetime64[ns]
dtype: object

### Memory Usage

In [104]:
df.memory_usage(deep=True)

Index        132
user_id       40
age           40
city         239
salary        40
joined_on     40
dtype: int64

Helps decide:
- dtype optimization
- chunking
- alternative tools

### Real-World Workflow
```python
df.head()
df.info()
df.isna().sum()
df.describe()
df.sample(5)
```

### Exercise 1
**Dataset:**
```python
import pandas as pd

df = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1005],
    "user_id": [201, 202, 203, 204, 205, 205],
    "order_amount": [2500, 1800, None, 3200, -500, 3200],
    "payment_mode": ["UPI", "Card", "UPI", None, "Cash", "Cash"],
    "order_date": ["2024-01-10", "2024-01-11", "2024-01-12", "invalid_date", "2024-01-14", "2024-01-14"]
})
```
1. Check:
   - df.shape
   - df.columns
   - df.head()

2. Answer:
   - How many rows & columns?
   - Does anything look suspicious immediately?

In [105]:
import pandas as pd

df = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1005],
    "user_id": [201, 202, 203, 204, 205, 205],
    "order_amount": [2500, 1800, None, 3200, -500, 3200],
    "payment_mode": ["UPI", "Card", "UPI", None, "Cash", "Cash"],
    "order_date": ["2024-01-10", "2024-01-11", "2024-01-12", "invalid_date", "2024-01-14", "2024-01-14"]
})

In [106]:
df.shape

(6, 5)

In [107]:
df.columns

Index(['order_id', 'user_id', 'order_amount', 'payment_mode', 'order_date'], dtype='object')

In [108]:
df.head()

   order_id  user_id  order_amount payment_mode    order_date
0      1001      201        2500.0          UPI    2024-01-10
1      1002      202        1800.0         Card    2024-01-11
2      1003      203           NaN          UPI    2024-01-12
3      1004      204        3200.0         None  invalid_date
4      1005      205        -500.0         Cash    2024-01-14

Suspicious:
- `order_amount` has `NaN` 
- `payment_mode` has `None` 
- `order_date` has `"invalid_date" `

### Exercise 2
1. Run 
   - `df.info()`
2. Answer:
   - Which columns have missing values?
   - Which dtypes look **wrong or dangerous**?
   - Which column would worry you the **most** in production?

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      6 non-null      int64
 1   user_id       6 non-null      int64
 2   order_amount  5 non-null      float64
 3   payment_mode  5 non-null      object
 4   order_date    6 non-null      object
dtypes: float64(1), int64(2), object(2)
memory usage: 372.0+ bytes

**Missing values**
- `order_amount`: 1 missing
- `payment_mode`: 1 missing

**Wrong / dangerous dtypes**
- `order_date -> object` (most dangerous)

**Column to worry about most**
- `order_date`

**Important:**
- Invalid dates are silent
- ML time features break
- Sorting & filtering becomes incorrect
- API serialization may lie

### Exercise 3
1. Run:
   - `df.isna().sum()`

2. Answer:
   - Which column has missing values?
   - Are these missing values **acceptable**, **suspicious**, or **critical**?

In [110]:
df.isna().sum()

order_id        0
user_id         0
order_amount    1
payment_mode    1
order_date      0
dtype: int64

**Conclusion:** these values are **suspicious, not acceptable**

- `order_amount` missing -> business decision needed
- `payment_mode` missing -> should almost never be missing

### Exercise 4
1. Inspect:
   - `df["order_amount"].describe()`

2. Answer:
   - Is every value logically valid?
   - Which value violates a business rule?

In [111]:
df["order_amount"].describe()

count       5.000000
mean     2040.000000
std      1533.949152
min      -500.000000
25%      1800.000000
50%      2500.000000
75%      3200.000000
max      3200.000000
Name: order_amount, dtype: float64

#### Critical violation
- min = -500

Correct identification

Negative `order_amount` is either a **refund or data bug** — never ignore it.

### Exercise 5
1. Check:
   - `f["order_id"].is_unique`

2. Answer:
   - Is this acceptable?
   - What kind of bug can this cause in:
       - ML?
       - APIs?
       - Analytics?

In [112]:
df["order_id"].is_unique

False

**Not Acceptable**

- APIs -> duplicate responses
- ML -> data leakage
- Analytics -> inflation

### Exercise 6
1. Run:
   - `df["payment_mode"].value_counts(dropna=False)`

2. Answer:
   - What issues do you see?
   - Is None acceptable here?

In [113]:
df["payment_mode"].value_counts(dropna=False)

payment_mode
UPI     2
Cash    2
Card    1
None    1
Name: count, dtype: int64

`None` is **not acceptable**

Payment mode missing could be due to failed transaction, partial record, etc, all are **high severity**.

### Exercise 7
1. Before converting anything, answer:
   - What is the dtype of order_date?
   - Why is this dangerous?
2. What might happen if someone blindly does:
   - `pd.to_datetime(df["order_date"])`

**dtype** of `order_date` is `object`

Performing operations on it will **Raise an Error** because of `invalid_date`

`ValueError: Unknown string format: invalid_date`