**GroupBy** as three steps:
```
SPLIT  →  APPLY  →  COMBINE
```

- **Split** data into groups
- **Apply** a function to each group
- **Combine** results back together

### Basic GroupBy

In [1]:
import pandas as pd

df = pd.DataFrame({
    "city": ["Pune", "Pune", "Mumbai", "Mumbai", "Delhi", "Delhi", "Delhi"],
    "user_id": [101, 102, 103, 104, 105, 106, 107],
    "age": [25, 35, 40, 60, 30, 45, 30],
    "salary": [50000, 70000, 80000, 90000, 60000, 75000, 65000]
})

#### Average salary per city

In [3]:
df.groupby("city")["salary"].mean()

city
Delhi     66666.666667
Mumbai    85000.000000
Pune      60000.000000
Name: salary, dtype: float64

Flow:
- Split by `city`
- Applied `mean`
- Combined into a Series

#### Multiple aggregations

In [5]:
df.groupby("city")["salary"].agg(["mean", "min", "max"])

                mean    min    max
city
Delhi   66666.666667  60000  75000
Mumbai  85000.000000  80000  90000
Pune    60000.000000  50000  70000

### GroupBy Multiple Columns

#### Group by city and age

In [6]:
df.groupby(["city", "age"])["salary"].mean()

city    age
Delhi   30     62500.0
        45     75000.0
Mumbai  40     80000.0
        60     90000.0
Pune    25     50000.0
        35     70000.0
Name: salary, dtype: float64

### Aggregation Multiple Columns

In [7]:
df.groupby("city").agg({
    "salary": ["mean", "max"],
    "age": "mean",
    "user_id": "count"
})

              salary          age user_id
                mean    max  mean   count
city
Delhi   66666.666667  75000  35.0       3
Mumbai  85000.000000  90000  50.0       2
Pune    60000.000000  70000  30.0       2

### Renaming Aggregated Columns

In [8]:
df.groupby("city").agg(
    avg_salary=("salary", "mean"),
    max_salary=("salary", "max"),
    user_count=("user_id", "count")
)

          avg_salary  max_salary  user_count
city
Delhi   66666.666667       75000           3
Mumbai  85000.000000       90000           2
Pune    60000.000000       70000           2

### `reset_index()`
GroupBy puts group keys into the **index**.

In [11]:
result = df.groupby("city").agg(
    avg_salary=("salary", "mean")
)
result

          avg_salary
city
Delhi   66666.666667
Mumbai  85000.000000
Pune    60000.000000

To convert back to normal DataFrame:

In [12]:
result.reset_index()

     city    avg_salary
0   Delhi  66666.666667
1  Mumbai  85000.000000
2    Pune  60000.000000

### `transform()` - Same Shape as Original

#### City-wise average salary per row

In [14]:
df["city_avg_salary"] = (
    df.groupby("city")["salary"].transform("mean")
)
df

     city  user_id  age  salary  city_avg_salary
0    Pune      101   25   50000     60000.000000
1    Pune      102   35   70000     60000.000000
2  Mumbai      103   40   80000     85000.000000
3  Mumbai      104   60   90000     85000.000000
4   Delhi      105   30   60000     66666.666667
5   Delhi      106   45   75000     66666.666667
6   Delhi      107   30   65000     66666.666667

| Method        | Output size      |
| ------------- | ---------------- |
| `agg()`       | Reduced          |
| `transform()` | Same as original |

### GroupBy + Filtering

#### Cities with average salary > 70000

In [17]:
city_avg = df.groupby("city")["salary"].mean()
city_avg[city_avg > 70000]

city
Mumbai    85000.0
Name: salary, dtype: float64

Or inline:

In [18]:
df.groupby("city").filter(lambda x: x["salary"].mean() > 70000)

     city  user_id  age  salary  city_avg_salary
2  Mumbai      103   40   80000          85000.0
3  Mumbai      104   60   90000          85000.0

### ML Feature Engineering Example

In [19]:
df.assign(
    city_salary_mean = lambda x: x.groupby("city")["salary"].transform("mean"),
    city_salary_std = lambda x: x.groupby("city")["salary"].transform("std"),
    salary_vs_city_avg = lambda x: x["salary"] - x.groupby("city")["salary"].transform("mean")
)

,city,user_id,age,salary,city_avg_salary,city_salary_mean,city_salary_std,salary_vs_city_avg
0,Pune,101,25,50000,60000.000000,60000.000000,14142.135624,-10000.000000
1,Pune,102,35,70000,60000.000000,60000.000000,14142.135624,10000.000000
2,Mumbai,103,40,80000,85000.000000,85000.000000,7071.067812,-5000.000000
3,Mumbai,104,60,90000,85000.000000,85000.000000,7071.067812,5000.000000
4,Delhi,105,30,60000,66666.666667,66666.666667,7637.626158,-6666.666667
5,Delhi,106,45,75000,66666.666667,66666.666667,7637.626158,8333.333333
6,Delhi,107,30,65000,66666.666667,66666.666667,7637.626158,-1666.666667

### Summary Table

| Goal                  | Use                     |
| --------------------- | ----------------------- |
| Aggregate             | `groupby().agg()`       |
| Row-level group stats | `groupby().transform()` |
| Complex logic         | `groupby().apply()`     |
| Filter groups         | `groupby().filter()`    |
| Clean output          | `reset_index()`         |

### Exercise 1
**DataSet**
```python
df = pd.DataFrame({
    "city": ["Pune", "Pune", "Mumbai", "Mumbai", "Delhi", "Delhi", "Delhi"],
    "user_id": [101, 102, 103, 104, 105, 106, 107],
    "age": [25, 35, 40, 60, 30, 45, 30],
    "salary": [50000, 70000, 80000, 90000, 60000, 75000, 65000]
})
```
1. Find the **average salary per city**
2. Find **min, max, and mean salary per city**

In [20]:
import pandas as pd

df = pd.DataFrame({
    "city": ["Pune", "Pune", "Mumbai", "Mumbai", "Delhi", "Delhi", "Delhi"],
    "user_id": [101, 102, 103, 104, 105, 106, 107],
    "age": [25, 35, 40, 60, 30, 45, 30],
    "salary": [50000, 70000, 80000, 90000, 60000, 75000, 65000]
})

In [22]:
df.groupby("city")["salary"].mean()

city
Delhi     66666.666667
Mumbai    85000.000000
Pune      60000.000000
Name: salary, dtype: float64

In [24]:
df.groupby("city")["salary"].agg(["mean", "max", "min"])

                mean    max    min
city
Delhi   66666.666667  75000  60000
Mumbai  85000.000000  90000  80000
Pune    60000.000000  70000  50000

### Exercise 2
Create a grouped DataFrame with columns:
- `avg_salary`
- `max_salary`
- `user_count`
- `avg_age`

In [25]:
grouped_df = (
    df.groupby("city")
    .agg(
        avg_salary=("salary", "mean"),
        max_salary=("salary", "max"),
        user_count=("user_id", "count"),
        avg_age=("age", "mean")
    )
)

grouped_df

          avg_salary  max_salary  user_count  avg_age
city
Delhi   66666.666667       75000           3     35.0
Mumbai  85000.000000       90000           2     50.0
Pune    60000.000000       70000           2     30.0

### Exercise 3
1. Check the index of the result from Exercise 2
2. Convert it back into a **flat DataFrame**

In [32]:
grouped_df = grouped_df.reset_index()
grouped_df

   index    city    avg_salary  max_salary  user_count  avg_age
0      0   Delhi  66666.666667       75000           3     35.0
1      1  Mumbai  85000.000000       90000           2     50.0
2      2    Pune  60000.000000       70000           2     30.0

### Exercise 4
1. Add a column `city_avg_salary`
2. Add a column `salary_diff_from_city_avg`
(`salary - city_avg_salary`)

In [33]:
df.assign(
    city_avg_salary = lambda x: x.groupby("city")["salary"].transform("mean"),
    salary_diff_from_city_avg = lambda x: x["salary"] - x.groupby("city")["salary"].transform("mean")
)

     city  user_id  age  salary  city_avg_salary  salary_diff_from_city_avg
0    Pune      101   25   50000     60000.000000              -10000.000000
1    Pune      102   35   70000     60000.000000               10000.000000
2  Mumbai      103   40   80000     85000.000000               -5000.000000
3  Mumbai      104   60   90000     85000.000000                5000.000000
4   Delhi      105   30   60000     66666.666667               -6666.666667
5   Delhi      106   45   75000     66666.666667                8333.333333
6   Delhi      107   30   65000     66666.666667               -1666.666667

### Exercise 5
1. Keep **only cities whose average salary > 70000**
2. Return the **original rows** for those cities

In [34]:
df.groupby("city").filter(lambda x: x["salary"].mean() > 70000)

     city  user_id  age  salary
2  Mumbai      103   40   80000
3  Mumbai      104   60   90000

### Exercise 6
For each city, return **only the row of the highest-paid user.**

In [35]:
result = (
    df.sort_values("salary", ascending=False)
    .groupby("city")
    .head(1)
)

result

     city  user_id  age  salary
3  Mumbai      104   60   90000
5   Delhi      106   45   75000
1    Pune      102   35   70000

### Exercise 7
1. Group by `city` and `age`
2. Compute **average salary** for each `(city, age)` pair

In [37]:
df.groupby(["city", "age"])["salary"].mean()

city    age
Delhi   30     62500.0
        45     75000.0
Mumbai  40     80000.0
        60     90000.0
Pune    25     50000.0
        35     70000.0
Name: salary, dtype: float64